### ISSUE TITLE
/Processes, styling

### ISSUE THREAD

**Issue by mcdonnelldean** [nearform/vidi-dashboard#111]
Answers on your notes,

* it'd be great to attach a class (now hardcoded) to `over limit` stat so it can be either green or red..
 - Added notes in #110 to do this work, do here also.

* collapsed view doesn't have more than uptime, but I think in reality it might need more. the question i'd have is which parts are crucial (it might be hard to reshuffle some w/o duplicating content)

 - Added these to /overview so you can work on them as is, I will basically use the same data and render  one or the other.

Screen looks good. I had to butcher the UI again to add more bits so it might be an idea to review the markup.

The data under event loop and memory usage could do with being tighter and smaller, like a compact row. I have more 'under chart' data coming soon. The data under here is a repeat of the chart so it can be much smaller that the regular stat rows.

I need to add the following section below event loop so will need some ui /styling to handle

### Execution
- 'full/path/to/node'
- 'full/path/to/script'

#### Args
- '-r'
- 'toolbag'

Which is how this, `node -r toolbag /server/start,js` is reported to the dashboard

Both the execution list and args sublist are basically the things you ran in the terminal but with full paths. There can be many of each so 1 per line is probably safest. The data here is 'second tier' it can be smaller than the regular data to save vertical space.

I'd say you could get both sections in one row if you went a 9 / 3 split of Execution / Args. The execution data is an array of scripts, the args is an array of args.

**Comment by thefoxis** [comment]
hopefully I got what you meant right, this is done now :ok_hand:
