### ISSUE TITLE
Style menu button into the header

### ISSUE THREAD

**Issue by mcdonnelldean** [nearform/vidi-dashboard#112]
I've been thinking about this one a lot lately, especially given the work on Concorda.

I think I would like to style the menu button into the header. This would give us the full viewport to work with. I think this makes it all a bit easier to right? The pages will all look uniform and the menu can just slide over the viewport?

Focus on the UI end, one the button is moved we can add back in the functionality.

**Comment by thefoxis** [comment]
the markup and visuals for sidebar are still there for presentation purposes. let me know in separate issue if to get rid of it :rocket:
