### ISSUE TITLE
Add ES6 for server side code

### ISSUE THREAD

**Issue by mcdonnelldean** [nearform/vidi-dashboard#28]
Right now only client code is transplied.

We probably need to clean up the npm scripts here too.

**Comment by AdrianRossouw** [comment]
well, unless we have a good reason to be running front-end code in the backend, I suspect it's best to limit ourselves to using whatever node 4.0 supports by default on the server side.

https://nodejs.org/en/docs/es6/

**Comment by mcdonnelldean** [comment]
@AdrianRossouw I'm happy enough to do it this way, how does that impact things like docker, is it just a case of hiding it all behind npm commands with those flags?

**Comment by AdrianRossouw** [comment]
well, it would mean requiring node 4.x minimum, which has that first list enabled without requiring any flags.

**Comment by mcdonnelldean** [comment]
Closing as answered above.
