### ISSUE TITLE
Move to Redux

### ISSUE THREAD

**Issue by mcdonnelldean** [nearform/vidi-dashboard#30]

**Comment by mcdonnelldean** [comment]
@AdrianRossouw I'm going to need some help here. I get what it's supposed to be but I just can't get my head into creating a basic flow.

**Comment by mcdonnelldean** [comment]
Closed by #41

**Comment by AdrianRossouw** [comment]
:+1:  :dancer: :clap:

**Comment by mcdonnelldean** [comment]
Little but of tidy work to do but it all works
