### ISSUE TITLE
Upgrade to hapi 12

### ISSUE THREAD

**Issue by geek** [nearform/vidi-dashboard#33]
https://github.com/hapijs/hapi/issues/2985

**Comment by mcdonnelldean** [comment]
@geek Waiting on hapi and nes, they have a dependency on 11.x

**Comment by mcdonnelldean** [comment]
@geek Any idea when Chairo will get updated?

**Comment by geek** [comment]
I just updated it last week. What feature are you waiting for?

Thanks,
Wyatt

**Comment by mcdonnelldean** [comment]
Hapi 12 in general 

Kindest Regards,

Dean

**Comment by mcdonnelldean** [comment]
@ckiss Can you take a look at this? We should be on the latest possible of everything.

**Comment by ckiss** [comment]
sure @mcdonnelldean
