### ISSUE TITLE
Webpack changes don't align to routes

### ISSUE THREAD

**Issue by mcdonnelldean** [nearform/vidi-dashboard#36]
@AdrianRossouw 

Our routes are set up to read files from folders ala

```
/css
/js
/img
```

See https://github.com/nearform/vidi-dashboard/blob/master/server/routes/client.js

We need to either change to output of webpack or the routes. @geek set the routes up originally. I think they are set up this way because edge cases in the greedy index route can cause it to be matched wrongly.

The greedy match is to handle routes from the client-side which react router is handling.

**Comment by AdrianRossouw** [comment]
can't you just replace that whole thing with a '/dist' and expose that?

**Comment by mcdonnelldean** [comment]
Closed via #38
