### ISSUE TITLE
Update vidi to use stylus via webpack

### ISSUE THREAD

**Issue by mcdonnelldean** [nearform/vidi-dashboard#49]
As like nodezoo-web

**Comment by ckiss** [comment]
@mcdonnelldean do you want it to be able to use others too? (less, sass)

**Comment by mcdonnelldean** [comment]
@ckiss yeah drop all the rest, same for nodezoo. Spoke to @thefoxis and we are going to go with Stylus.

**Comment by ckiss** [comment]
cool, will do. thanks @mcdonnelldean

**Comment by mcdonnelldean** [comment]
Closed by #52
