### ISSUE TITLE
Allow styling for form error messages

### ISSUE THREAD

**Issue by thefoxis** [nearform/vidi-dashboard#61]
Currently the way form validation works when you submit an invalid password it replaces the text from "Login" to the error message. That's a nifty way to do it but it'd be great to be able to style it more distinctively as en error message. Proposed solutions:

* either attach a class to the `h2` [here](https://github.com/nearform/vidi-dashboard/blob/ui-redo/client/containers/login.js#L32) (eg. `alert alert-warn`)
* create a container above the `h2` with the error message (same classes as above)

#53

**Comment by mcdonnelldean** [comment]
@thefoxis Let's go with changing the class. I'll change it add add comments so you can see how the change happens.

**Comment by mcdonnelldean** [comment]
I did the first option, but we can change to the second one if you prefer. https://github.com/nearform/vidi-dashboard/commit/bb871e547e65690b97d0541a286cdbfe6db02434
