### ISSUE TITLE
Better font?

### ISSUE THREAD

**Issue by mcdonnelldean** [nearform/vidi-dashboard#63]
The font looks a bit heavy. Do do you recommend keeping it or changing to something lighter? I don't want to waste your time bikeshedding fonts so I'm happy for you to choose something you feel would better fit your design. Or leave it if you like it :D

**Comment by thefoxis** [comment]
@mcdonnelldean — I changed it from regular to light. Another thing we could do is switch from `optimizeSpeed` to `optimizeLegibility` which aids with font rendering a little bit as well (might have some performance downsides, but I don't think it would in this use case). closing for now, but feel free to reopen if you feel like it's still no good
