### ISSUE TITLE
Tabs not loading without browser refresh

### ISSUE THREAD

**Issue by shanel262** [nearform/vidi-dashboard#76]
I'm having an issue when I try to navigate between tabs on vidi. When I log in I'm brought to overview by default and when I choose any other tab the url changes but the view does not. In order to fix this I have to refresh the browser. I am then free to move between tabs but if I go back to overview the same problem arises.

![beforerefresh](https://cloud.githubusercontent.com/assets/10059043/12580523/34eb061a-c428-11e5-913a-b4a0f56857ad.png) -before browser reload

![afterrefresh](https://cloud.githubusercontent.com/assets/10059043/12580526/3c90933a-c428-11e5-9176-e2d35ef0c5e4.png) -after browser reload

**Comment by mcdonnelldean** [comment]
@shanel262 Can you open the browser window and see if you are getting an error on the client side when you change routes but before you refresh?

**Comment by shanel262** [comment]
@mcdonnelldean 
![vidierror](https://cloud.githubusercontent.com/assets/10059043/12580699/8495fcc8-c429-11e5-8eb4-7365873f09cc.png)

**Comment by mcdonnelldean** [comment]
Same as #86 Closing
