### ISSUE TITLE
Moving from Overview to another tab doesn't change content unless browser refreshes

### ISSUE THREAD

**Issue by CodeWriterWriter** [nearform/vidi-dashboard#86]
When starting off on the Overview page, navigating to another page will change the URL, but not the content of the window. Refreshing on a non-Overview page will fix this.

**Comment by CodeWriterWriter** [comment]
This only occurs when there are no graphs on the overview page

**Comment by mcdonnelldean** [comment]
Note to self, this is due to the charts crashing the router due to bad blank data.

**Comment by mcdonnelldean** [comment]
No longer relavent
