### ISSUE TITLE
Break down the vidi plugin

### ISSUE THREAD

**Issue by mcdonnelldean** [nearform/vidi-dashboard#91]
Right now the plugin providing stats sends them over one pattern. We need to split these out so that you ask for each metric individually. We should also have the ability to support the following using simple key-value options

- change query from 120s to any number
- If grouped by time, change the resolution from 1s to any number
- Change support sum, avg, median, from same pattern

The socket actions and the timeout right now won't handle these changes, we will need to develop a more specific set of actions (vidi) to allow one socket per data. The timer code on the server also needs to be reworked as it's a bit basic. It may make more sense to have the timeout on the client which emits subscription updates. This would allow the client to throttle the data. Basic thinking here is.

- client subscribe
- client gets data
- client sends another request once it has data
- cycle repeats until unsubscribe

**Comment by salmanm** [comment]
> The timer code on the server also needs to be reworked as it's a bit basic. It may make more sense to have the timeout on the client which emits subscription updates.

@mcdonnelldean Does it mean server won't publish at all until client asks? If yes, then we might end-up using one-to-one communication using `client.message(<get_data>, function (err, <here_it_is>) { })`. Currently we're doing a `server.publish`. Which i believe sends data to all connected clients.

Generally of course, server push is a good idea for realtime data. Although currently we have a `setInterval` but it would be changed right! I would think of doing `server.publish` on some event may be, after some operation gathered new data that should be reflected into the dashboard. 

WDYT?

**Comment by mcdonnelldean** [comment]
@salmanm So here's my issue,

We need to be able to subscribe to the same set of data in different ways. So we could have the following on screen.

- Flow rate sum per min / / sec
- Flow rate sum per min / 5 sec
- Flow rate avg per hour

I'm pretty open to how we achieve it but we basically need to be able to subscribe to real-time feeds of data in different shapes. Any ideas?
