### ISSUE TITLE
RFC: Shall we use immutable.js for reducer states?

### ISSUE THREAD

**Issue by salmanm** [nearform/vidi-dashboard#97]
Using `Object.assign` and ES7 spread operators are good. But I feel immutability should not be implemented by convention, it should be enforced. Moreover, using immutable.js library gives a cleaner interface to update objects using `setIn`, `updateIn` etc

**Comment by mcdonnelldean** [comment]
@salmanm Can you show me an example of the code somewhere so I understand the change impact?

**Comment by salmanm** [comment]
Sure, For an initial state of 

```
const initialState = {
  profile: {
    some: 'thing',
    someOther: 'thing',
    identities: []
  }
};
```

The following
```
  return Object.assign({}, state, {
    profile: {
      ...state.profile,
      identities: [...action.identities]
    }
  })
```
becomes this
```
  return state.setIn(['profile', 'identities'], action.identities);
```

**Comment by mcdonnelldean** [comment]
Ah nice! Yeah that looks neat and if it enforces immutability more for it. I'm happy to see this change.

**Comment by salmanm** [comment]
:+1:  Cool, a slightly bigger tech debt, let's take it after I finish timer logic.

Just thought of adding one more thing. Reading state in the react-redux's `connect` is good, but if someone by mistake tries to set the value there :astonished: boom, we got a mutated state.

**Comment by mcdonnelldean** [comment]
Closing as we will do without for now.
